# OpenJDK 21 기반 이미지 사용
FROM eclipse-temurin:21-jdk

#ARG PROD_MYSQL_URL=${PROD_MYSQL_URL}
#ARG MYSQL_USERNAME=${MYSQL_USERNAME}
#ARG MYSQL_PASSWORD=${MYSQL_PASSWORD}
#ARG GOOGLE_EMAIL_USERNAME=${GOOGLE_EMAIL_USERNAME}
#ARG GOOGLE_EMAIL_PASSWORD=${GOOGLE_EMAIL_PASSWORD}
#
#ENV PROD_MYSQL_URL=${PROD_MYSQL_URL}
#ENV MYSQL_USERNAME=${MYSQL_USERNAME}
#ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
#ENV GOOGLE_EMAIL_USERNAME=${GOOGLE_EMAIL_USERNAME}
#ENV GOOGLE_EMAIL_PASSWORD=${GOOGLE_EMAIL_PASSWORD}

WORKDIR /app

# JAR 파일 복사
COPY target/eventor-back-0.0.1-SNAPSHOT.jar eventor-back.jar

# 애플리케이션 실행
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "eventor-back.jar"]