spring:
  # 재시작 및 라이브 리로드 활성화
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/eventor
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

    dbcp2:
      initial-size: 50    # 초기로 생성할 연결의 수를 설정합니다.
      max-total: 50   # 풀에서 유지할 수 있는 최대 연결 수를 설정합니다.
      max-idle: 50   # 유휴 상태로 유지할 최대 연결 수를 설정합니다.
      min-idle: 50    # 유휴 상태로 유지할 최소 연결 수를 설정합니다.
      test-on-borrow: true    # 풀에서 연결을 빌릴 때마다 해당 연결이 유효한지 검증할지 여부를 설정합니다.
      validation-query: SELECT 1    # 연결 유효성을 검사하기 위해 실행할 SQL 쿼리를 설정합니다.

  # SQL 초기화 설정
  sql:
    init:
      mode: always

  # JPA 설정
  jpa:
    open-in-view: false
    show-sql: true    # Hibernate 가 생성하는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true    # SQL 쿼리를 보기 쉽게 포맷팅하여 출력합니다.
        use_sql_comments: true    # SQL 쿼리에 주석을 추가
        highlight_sql: true   # SQL 쿼리를 하이라이트하여 출력
        auto_quote_keyword: true    # SQL 키워드를 자동으로 인용하여 SQL 구문 오류를 방지합니다.
    hibernate:
      ddl-auto: update #validate로 변경 예정
    defer-datasource-initialization: true   # 데이터 소스 초기화를 지연시킵니다. 이는 데이터베이스 연결을 설정하기 전에 다른 초기화 로직을 완료할 수 있게 합니다.

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework:
      transaction:
        interceptor: trace
        security: debug
        web: debug

upload:
  path: C:/Users/dlrud/Desktop/infra/