spring:
  datasource:
    url: ${DEV_MYSQL_URL}
    dbcp2:
      username: ${MYSQL_USERNAME}
      password: ${DEV_MYSQL_PASSWORD}

  data:
    redis:
      host: localhost
      password: ${REDIS_PASSWORD}
  
  # JPA 설정
  jpa:
    show-sql: true    # Hibernate 가 생성하는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true    # SQL 쿼리를 보기 쉽게 포맷팅하여 출력합니다.
        use_sql_comments: true    # SQL 쿼리에 주석을 추가
        highlight_sql: true   # SQL 쿼리를 하이라이트하여 출력
    hibernate:
      ddl-auto: update #validate로 변경 예정

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework:
      transaction:
        interceptor: trace
        security: debug
        web: debug

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
  instance:
    prefer-ip-address: true

upload:
  domainUrl: https://localhost
  path: C:/Users/dlrud/Desktop/infra/