spring:
  # 재시작 및 라이브 리로드 활성화
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/eventor

  data:
    redis:
      host: localhost

  # JPA 설정
  jpa:
    show-sql: true    # Hibernate 가 생성하는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true    # SQL 쿼리를 보기 쉽게 포맷팅하여 출력합니다.
        use_sql_comments: true    # SQL 쿼리에 주석을 추가
        highlight_sql: true   # SQL 쿼리를 하이라이트하여 출력
    hibernate:
      ddl-auto: update #validate로 변경 예정

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework:
      transaction:
        interceptor: trace
        security: debug
        web: debug

upload:
  path: C:/Users/dlrud/Desktop/infra/